version: '3'

services:
  filemover_fastapi:
    build: fastapi/
    ports: 
      - 9001:9001
    networks:
      - deploy_network
    volumes:
      - ~/music/folder_source:/app/source:z
      - ~/music/folder_target:/app/target:z
    container_name: filemover_fastapi
    restart: always

  filemover_streamlit:
    build: streamlit/
    depends_on:
      - filemover_fastapi
    ports: 
        - 9000:9000
    networks:
      - deploy_network
    container_name: filemover_streamlit
    restart: always

networks:
  deploy_network:
    driver: bridge