URL_BACKEND="http://filemover_fastapi:9001/"

IS_DEBUG = True

TAG_DATE_BEGIN=1900

TAG_TARCK_END=20

TAG_OPTION_WHIP=True
TAG_OPTION_MOVE_SOURCE_TO_TARGET=True
TAG_OPTION_MOVE_TARGET_TO_SOURCE=False

TAG_OPTION_MPD_UPDATE=True
