DATE_FORMAT = "%Y-%m-%d"

ENC_TYPE = 'utf-8'

PATH_TYPE_FOLDER = "FOLDER"
PATH_TYPE_FILE = "FILE"


PATH_LOCATION_SOURCE = "SOURCE"
PATH_LOCATION_TARGET = "TARGET"

RESULT_SUCCESS = "SUCCESS"
RESULT_FAIL = "FAIL"

FOLDER_ACTION_RENAME_CURRENT="R"
FOLDER_ACTION_ADD_SUB_FOLDER="A"
FOLDER_ACTION_DELETE_CURRENT="D"
FOLDER_ACTION_UPLOAD_FILE="U"