S_CURRENT_SOURCE_FOLDER = "S_CURRENT_SOURCE_FOLDER"
S_CURRENT_TARGET_FOLDER = "S_CURRENT_TARGET_FOLDER"

S_CURRENT_SOURCE_FOLDER_DISPLAY = "S_CURRENT_SOURCE_FOLDER_DISPLAY"
S_CURRENT_TARGET_FOLDER_DISPLAY = "S_CURRENT_TARGET_FOLDER_DISPLAY"

S_CURRENT_TAG_ITEM = "S_CURRENT_TAG_ITEM"
S_CURRENT_FILE_ITEM = "S_CURRENT_FILE_ITEM"
S_CURRENT_ROOT_TYPE = "S_CURRENT_ROOT_TYPE"

S_SB_STATE = "S_SB_STATE"
S_SB_TAG_SELECT = "S_SB_TAG_SELECT"
S_SB_FOLDER_SELECT = "S_SB_FOLDER_SELECT"

