S_CURRENT_SOURCE_FOLDER = "S_CURRENT_SOURCE_FOLDER"
S_CURRENT_TARGET_FOLDER = "S_CURRENT_TARGET_FOLDER"

S_CURRENT_SOURCE_FOLDER_DISPLAY = "S_CURRENT_SOURCE_FOLDER_DISPLAY"
S_CURRENT_TARGET_FOLDER_DISPLAY = "S_CURRENT_TARGET_FOLDER_DISPLAY"


S_CURRENT_TAG_ITEM = "S_CURRENT_TAG_ITEM"